package com.sz.water.entity;

import java.util.Date;

public class CheckMatterItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter_item.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter_item.imgUrl
     *
     * @mbg.generated
     */
    private String imgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter_item.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter_item.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter_item.creatTime
     *
     * @mbg.generated
     */
    private Date creattime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter_item.matterID
     *
     * @mbg.generated
     */
    private Long matterid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter_item.id
     *
     * @return the value of check_matter_item.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter_item.id
     *
     * @param id the value for check_matter_item.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter_item.imgUrl
     *
     * @return the value of check_matter_item.imgUrl
     *
     * @mbg.generated
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter_item.imgUrl
     *
     * @param imgurl the value for check_matter_item.imgUrl
     *
     * @mbg.generated
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter_item.remarks
     *
     * @return the value of check_matter_item.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter_item.remarks
     *
     * @param remarks the value for check_matter_item.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter_item.sort
     *
     * @return the value of check_matter_item.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter_item.sort
     *
     * @param sort the value for check_matter_item.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter_item.creatTime
     *
     * @return the value of check_matter_item.creatTime
     *
     * @mbg.generated
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter_item.creatTime
     *
     * @param creattime the value for check_matter_item.creatTime
     *
     * @mbg.generated
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter_item.matterID
     *
     * @return the value of check_matter_item.matterID
     *
     * @mbg.generated
     */
    public Long getMatterid() {
        return matterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter_item.matterID
     *
     * @param matterid the value for check_matter_item.matterID
     *
     * @mbg.generated
     */
    public void setMatterid(Long matterid) {
        this.matterid = matterid;
    }
}