package com.sz.water.entity;

public class CheckMatter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.DF_ScoreA
     *
     * @mbg.generated
     */
    private Double dfScorea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.DF_ScoreB
     *
     * @mbg.generated
     */
    private Double dfScoreb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.DF_ScoreC
     *
     * @mbg.generated
     */
    private Double dfScorec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.DF_ScoreD
     *
     * @mbg.generated
     */
    private Double dfScored;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.DF_ScoreE
     *
     * @mbg.generated
     */
    private Double dfScoree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.OP_ScoreA
     *
     * @mbg.generated
     */
    private Double opScorea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.OP_ScoreB
     *
     * @mbg.generated
     */
    private Double opScoreb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.OP_ScoreC
     *
     * @mbg.generated
     */
    private Double opScorec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.AD_ScoreA
     *
     * @mbg.generated
     */
    private Double adScorea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.AD_ScoreB
     *
     * @mbg.generated
     */
    private Double adScoreb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.AD_ScoreC
     *
     * @mbg.generated
     */
    private Double adScorec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.AD_ScoreD
     *
     * @mbg.generated
     */
    private Double adScored;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.permitNo
     *
     * @mbg.generated
     */
    private String permitno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.drainageNumber
     *
     * @mbg.generated
     */
    private Double drainagenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterA
     *
     * @mbg.generated
     */
    private String mattera;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterAStr
     *
     * @mbg.generated
     */
    private String matterastr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterB
     *
     * @mbg.generated
     */
    private String matterb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterBStr
     *
     * @mbg.generated
     */
    private String matterbstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterC
     *
     * @mbg.generated
     */
    private String matterc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterCStr
     *
     * @mbg.generated
     */
    private String mattercstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterD
     *
     * @mbg.generated
     */
    private String matterd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterDStr
     *
     * @mbg.generated
     */
    private String matterdstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterE
     *
     * @mbg.generated
     */
    private String mattere;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterEStr
     *
     * @mbg.generated
     */
    private String matterestr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterF
     *
     * @mbg.generated
     */
    private String matterf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterFStr
     *
     * @mbg.generated
     */
    private String matterfstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterG
     *
     * @mbg.generated
     */
    private String matterg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterGStr
     *
     * @mbg.generated
     */
    private String mattergstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterH
     *
     * @mbg.generated
     */
    private String matterh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterHStr
     *
     * @mbg.generated
     */
    private String matterhstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterI
     *
     * @mbg.generated
     */
    private String matteri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterIStr
     *
     * @mbg.generated
     */
    private String matteristr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterJ
     *
     * @mbg.generated
     */
    private String matterj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterJStr
     *
     * @mbg.generated
     */
    private String matterjstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterK
     *
     * @mbg.generated
     */
    private String matterk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterKStr
     *
     * @mbg.generated
     */
    private String matterkstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterL
     *
     * @mbg.generated
     */
    private String matterl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterLStr
     *
     * @mbg.generated
     */
    private String matterlstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterM
     *
     * @mbg.generated
     */
    private String matterm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterMStr
     *
     * @mbg.generated
     */
    private String mattermstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterN
     *
     * @mbg.generated
     */
    private String mattern;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterNStr
     *
     * @mbg.generated
     */
    private String matternstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterO
     *
     * @mbg.generated
     */
    private String mattero;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterOStr
     *
     * @mbg.generated
     */
    private String matterostr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterP
     *
     * @mbg.generated
     */
    private String matterp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterPStr
     *
     * @mbg.generated
     */
    private String matterpstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterQ
     *
     * @mbg.generated
     */
    private String matterq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterQStr
     *
     * @mbg.generated
     */
    private String matterqstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterR
     *
     * @mbg.generated
     */
    private String matterr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterRStr
     *
     * @mbg.generated
     */
    private String matterrstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterS
     *
     * @mbg.generated
     */
    private String matters;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.matterSStr
     *
     * @mbg.generated
     */
    private String mattersstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.autographURL
     *
     * @mbg.generated
     */
    private String autographurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_matter.allocationID
     *
     * @mbg.generated
     */
    private Long allocationid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.id
     *
     * @return the value of check_matter.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.id
     *
     * @param id the value for check_matter.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.DF_ScoreA
     *
     * @return the value of check_matter.DF_ScoreA
     *
     * @mbg.generated
     */
    public Double getDfScorea() {
        return dfScorea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.DF_ScoreA
     *
     * @param dfScorea the value for check_matter.DF_ScoreA
     *
     * @mbg.generated
     */
    public void setDfScorea(Double dfScorea) {
        this.dfScorea = dfScorea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.DF_ScoreB
     *
     * @return the value of check_matter.DF_ScoreB
     *
     * @mbg.generated
     */
    public Double getDfScoreb() {
        return dfScoreb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.DF_ScoreB
     *
     * @param dfScoreb the value for check_matter.DF_ScoreB
     *
     * @mbg.generated
     */
    public void setDfScoreb(Double dfScoreb) {
        this.dfScoreb = dfScoreb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.DF_ScoreC
     *
     * @return the value of check_matter.DF_ScoreC
     *
     * @mbg.generated
     */
    public Double getDfScorec() {
        return dfScorec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.DF_ScoreC
     *
     * @param dfScorec the value for check_matter.DF_ScoreC
     *
     * @mbg.generated
     */
    public void setDfScorec(Double dfScorec) {
        this.dfScorec = dfScorec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.DF_ScoreD
     *
     * @return the value of check_matter.DF_ScoreD
     *
     * @mbg.generated
     */
    public Double getDfScored() {
        return dfScored;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.DF_ScoreD
     *
     * @param dfScored the value for check_matter.DF_ScoreD
     *
     * @mbg.generated
     */
    public void setDfScored(Double dfScored) {
        this.dfScored = dfScored;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.DF_ScoreE
     *
     * @return the value of check_matter.DF_ScoreE
     *
     * @mbg.generated
     */
    public Double getDfScoree() {
        return dfScoree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.DF_ScoreE
     *
     * @param dfScoree the value for check_matter.DF_ScoreE
     *
     * @mbg.generated
     */
    public void setDfScoree(Double dfScoree) {
        this.dfScoree = dfScoree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.OP_ScoreA
     *
     * @return the value of check_matter.OP_ScoreA
     *
     * @mbg.generated
     */
    public Double getOpScorea() {
        return opScorea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.OP_ScoreA
     *
     * @param opScorea the value for check_matter.OP_ScoreA
     *
     * @mbg.generated
     */
    public void setOpScorea(Double opScorea) {
        this.opScorea = opScorea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.OP_ScoreB
     *
     * @return the value of check_matter.OP_ScoreB
     *
     * @mbg.generated
     */
    public Double getOpScoreb() {
        return opScoreb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.OP_ScoreB
     *
     * @param opScoreb the value for check_matter.OP_ScoreB
     *
     * @mbg.generated
     */
    public void setOpScoreb(Double opScoreb) {
        this.opScoreb = opScoreb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.OP_ScoreC
     *
     * @return the value of check_matter.OP_ScoreC
     *
     * @mbg.generated
     */
    public Double getOpScorec() {
        return opScorec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.OP_ScoreC
     *
     * @param opScorec the value for check_matter.OP_ScoreC
     *
     * @mbg.generated
     */
    public void setOpScorec(Double opScorec) {
        this.opScorec = opScorec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.AD_ScoreA
     *
     * @return the value of check_matter.AD_ScoreA
     *
     * @mbg.generated
     */
    public Double getAdScorea() {
        return adScorea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.AD_ScoreA
     *
     * @param adScorea the value for check_matter.AD_ScoreA
     *
     * @mbg.generated
     */
    public void setAdScorea(Double adScorea) {
        this.adScorea = adScorea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.AD_ScoreB
     *
     * @return the value of check_matter.AD_ScoreB
     *
     * @mbg.generated
     */
    public Double getAdScoreb() {
        return adScoreb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.AD_ScoreB
     *
     * @param adScoreb the value for check_matter.AD_ScoreB
     *
     * @mbg.generated
     */
    public void setAdScoreb(Double adScoreb) {
        this.adScoreb = adScoreb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.AD_ScoreC
     *
     * @return the value of check_matter.AD_ScoreC
     *
     * @mbg.generated
     */
    public Double getAdScorec() {
        return adScorec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.AD_ScoreC
     *
     * @param adScorec the value for check_matter.AD_ScoreC
     *
     * @mbg.generated
     */
    public void setAdScorec(Double adScorec) {
        this.adScorec = adScorec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.AD_ScoreD
     *
     * @return the value of check_matter.AD_ScoreD
     *
     * @mbg.generated
     */
    public Double getAdScored() {
        return adScored;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.AD_ScoreD
     *
     * @param adScored the value for check_matter.AD_ScoreD
     *
     * @mbg.generated
     */
    public void setAdScored(Double adScored) {
        this.adScored = adScored;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.permitNo
     *
     * @return the value of check_matter.permitNo
     *
     * @mbg.generated
     */
    public String getPermitno() {
        return permitno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.permitNo
     *
     * @param permitno the value for check_matter.permitNo
     *
     * @mbg.generated
     */
    public void setPermitno(String permitno) {
        this.permitno = permitno == null ? null : permitno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.drainageNumber
     *
     * @return the value of check_matter.drainageNumber
     *
     * @mbg.generated
     */
    public Double getDrainagenumber() {
        return drainagenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.drainageNumber
     *
     * @param drainagenumber the value for check_matter.drainageNumber
     *
     * @mbg.generated
     */
    public void setDrainagenumber(Double drainagenumber) {
        this.drainagenumber = drainagenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterA
     *
     * @return the value of check_matter.matterA
     *
     * @mbg.generated
     */
    public String getMattera() {
        return mattera;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterA
     *
     * @param mattera the value for check_matter.matterA
     *
     * @mbg.generated
     */
    public void setMattera(String mattera) {
        this.mattera = mattera == null ? null : mattera.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterAStr
     *
     * @return the value of check_matter.matterAStr
     *
     * @mbg.generated
     */
    public String getMatterastr() {
        return matterastr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterAStr
     *
     * @param matterastr the value for check_matter.matterAStr
     *
     * @mbg.generated
     */
    public void setMatterastr(String matterastr) {
        this.matterastr = matterastr == null ? null : matterastr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterB
     *
     * @return the value of check_matter.matterB
     *
     * @mbg.generated
     */
    public String getMatterb() {
        return matterb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterB
     *
     * @param matterb the value for check_matter.matterB
     *
     * @mbg.generated
     */
    public void setMatterb(String matterb) {
        this.matterb = matterb == null ? null : matterb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterBStr
     *
     * @return the value of check_matter.matterBStr
     *
     * @mbg.generated
     */
    public String getMatterbstr() {
        return matterbstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterBStr
     *
     * @param matterbstr the value for check_matter.matterBStr
     *
     * @mbg.generated
     */
    public void setMatterbstr(String matterbstr) {
        this.matterbstr = matterbstr == null ? null : matterbstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterC
     *
     * @return the value of check_matter.matterC
     *
     * @mbg.generated
     */
    public String getMatterc() {
        return matterc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterC
     *
     * @param matterc the value for check_matter.matterC
     *
     * @mbg.generated
     */
    public void setMatterc(String matterc) {
        this.matterc = matterc == null ? null : matterc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterCStr
     *
     * @return the value of check_matter.matterCStr
     *
     * @mbg.generated
     */
    public String getMattercstr() {
        return mattercstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterCStr
     *
     * @param mattercstr the value for check_matter.matterCStr
     *
     * @mbg.generated
     */
    public void setMattercstr(String mattercstr) {
        this.mattercstr = mattercstr == null ? null : mattercstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterD
     *
     * @return the value of check_matter.matterD
     *
     * @mbg.generated
     */
    public String getMatterd() {
        return matterd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterD
     *
     * @param matterd the value for check_matter.matterD
     *
     * @mbg.generated
     */
    public void setMatterd(String matterd) {
        this.matterd = matterd == null ? null : matterd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterDStr
     *
     * @return the value of check_matter.matterDStr
     *
     * @mbg.generated
     */
    public String getMatterdstr() {
        return matterdstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterDStr
     *
     * @param matterdstr the value for check_matter.matterDStr
     *
     * @mbg.generated
     */
    public void setMatterdstr(String matterdstr) {
        this.matterdstr = matterdstr == null ? null : matterdstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterE
     *
     * @return the value of check_matter.matterE
     *
     * @mbg.generated
     */
    public String getMattere() {
        return mattere;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterE
     *
     * @param mattere the value for check_matter.matterE
     *
     * @mbg.generated
     */
    public void setMattere(String mattere) {
        this.mattere = mattere == null ? null : mattere.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterEStr
     *
     * @return the value of check_matter.matterEStr
     *
     * @mbg.generated
     */
    public String getMatterestr() {
        return matterestr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterEStr
     *
     * @param matterestr the value for check_matter.matterEStr
     *
     * @mbg.generated
     */
    public void setMatterestr(String matterestr) {
        this.matterestr = matterestr == null ? null : matterestr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterF
     *
     * @return the value of check_matter.matterF
     *
     * @mbg.generated
     */
    public String getMatterf() {
        return matterf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterF
     *
     * @param matterf the value for check_matter.matterF
     *
     * @mbg.generated
     */
    public void setMatterf(String matterf) {
        this.matterf = matterf == null ? null : matterf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterFStr
     *
     * @return the value of check_matter.matterFStr
     *
     * @mbg.generated
     */
    public String getMatterfstr() {
        return matterfstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterFStr
     *
     * @param matterfstr the value for check_matter.matterFStr
     *
     * @mbg.generated
     */
    public void setMatterfstr(String matterfstr) {
        this.matterfstr = matterfstr == null ? null : matterfstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterG
     *
     * @return the value of check_matter.matterG
     *
     * @mbg.generated
     */
    public String getMatterg() {
        return matterg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterG
     *
     * @param matterg the value for check_matter.matterG
     *
     * @mbg.generated
     */
    public void setMatterg(String matterg) {
        this.matterg = matterg == null ? null : matterg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterGStr
     *
     * @return the value of check_matter.matterGStr
     *
     * @mbg.generated
     */
    public String getMattergstr() {
        return mattergstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterGStr
     *
     * @param mattergstr the value for check_matter.matterGStr
     *
     * @mbg.generated
     */
    public void setMattergstr(String mattergstr) {
        this.mattergstr = mattergstr == null ? null : mattergstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterH
     *
     * @return the value of check_matter.matterH
     *
     * @mbg.generated
     */
    public String getMatterh() {
        return matterh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterH
     *
     * @param matterh the value for check_matter.matterH
     *
     * @mbg.generated
     */
    public void setMatterh(String matterh) {
        this.matterh = matterh == null ? null : matterh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterHStr
     *
     * @return the value of check_matter.matterHStr
     *
     * @mbg.generated
     */
    public String getMatterhstr() {
        return matterhstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterHStr
     *
     * @param matterhstr the value for check_matter.matterHStr
     *
     * @mbg.generated
     */
    public void setMatterhstr(String matterhstr) {
        this.matterhstr = matterhstr == null ? null : matterhstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterI
     *
     * @return the value of check_matter.matterI
     *
     * @mbg.generated
     */
    public String getMatteri() {
        return matteri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterI
     *
     * @param matteri the value for check_matter.matterI
     *
     * @mbg.generated
     */
    public void setMatteri(String matteri) {
        this.matteri = matteri == null ? null : matteri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterIStr
     *
     * @return the value of check_matter.matterIStr
     *
     * @mbg.generated
     */
    public String getMatteristr() {
        return matteristr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterIStr
     *
     * @param matteristr the value for check_matter.matterIStr
     *
     * @mbg.generated
     */
    public void setMatteristr(String matteristr) {
        this.matteristr = matteristr == null ? null : matteristr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterJ
     *
     * @return the value of check_matter.matterJ
     *
     * @mbg.generated
     */
    public String getMatterj() {
        return matterj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterJ
     *
     * @param matterj the value for check_matter.matterJ
     *
     * @mbg.generated
     */
    public void setMatterj(String matterj) {
        this.matterj = matterj == null ? null : matterj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterJStr
     *
     * @return the value of check_matter.matterJStr
     *
     * @mbg.generated
     */
    public String getMatterjstr() {
        return matterjstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterJStr
     *
     * @param matterjstr the value for check_matter.matterJStr
     *
     * @mbg.generated
     */
    public void setMatterjstr(String matterjstr) {
        this.matterjstr = matterjstr == null ? null : matterjstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterK
     *
     * @return the value of check_matter.matterK
     *
     * @mbg.generated
     */
    public String getMatterk() {
        return matterk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterK
     *
     * @param matterk the value for check_matter.matterK
     *
     * @mbg.generated
     */
    public void setMatterk(String matterk) {
        this.matterk = matterk == null ? null : matterk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterKStr
     *
     * @return the value of check_matter.matterKStr
     *
     * @mbg.generated
     */
    public String getMatterkstr() {
        return matterkstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterKStr
     *
     * @param matterkstr the value for check_matter.matterKStr
     *
     * @mbg.generated
     */
    public void setMatterkstr(String matterkstr) {
        this.matterkstr = matterkstr == null ? null : matterkstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterL
     *
     * @return the value of check_matter.matterL
     *
     * @mbg.generated
     */
    public String getMatterl() {
        return matterl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterL
     *
     * @param matterl the value for check_matter.matterL
     *
     * @mbg.generated
     */
    public void setMatterl(String matterl) {
        this.matterl = matterl == null ? null : matterl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterLStr
     *
     * @return the value of check_matter.matterLStr
     *
     * @mbg.generated
     */
    public String getMatterlstr() {
        return matterlstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterLStr
     *
     * @param matterlstr the value for check_matter.matterLStr
     *
     * @mbg.generated
     */
    public void setMatterlstr(String matterlstr) {
        this.matterlstr = matterlstr == null ? null : matterlstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterM
     *
     * @return the value of check_matter.matterM
     *
     * @mbg.generated
     */
    public String getMatterm() {
        return matterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterM
     *
     * @param matterm the value for check_matter.matterM
     *
     * @mbg.generated
     */
    public void setMatterm(String matterm) {
        this.matterm = matterm == null ? null : matterm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterMStr
     *
     * @return the value of check_matter.matterMStr
     *
     * @mbg.generated
     */
    public String getMattermstr() {
        return mattermstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterMStr
     *
     * @param mattermstr the value for check_matter.matterMStr
     *
     * @mbg.generated
     */
    public void setMattermstr(String mattermstr) {
        this.mattermstr = mattermstr == null ? null : mattermstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterN
     *
     * @return the value of check_matter.matterN
     *
     * @mbg.generated
     */
    public String getMattern() {
        return mattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterN
     *
     * @param mattern the value for check_matter.matterN
     *
     * @mbg.generated
     */
    public void setMattern(String mattern) {
        this.mattern = mattern == null ? null : mattern.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterNStr
     *
     * @return the value of check_matter.matterNStr
     *
     * @mbg.generated
     */
    public String getMatternstr() {
        return matternstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterNStr
     *
     * @param matternstr the value for check_matter.matterNStr
     *
     * @mbg.generated
     */
    public void setMatternstr(String matternstr) {
        this.matternstr = matternstr == null ? null : matternstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterO
     *
     * @return the value of check_matter.matterO
     *
     * @mbg.generated
     */
    public String getMattero() {
        return mattero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterO
     *
     * @param mattero the value for check_matter.matterO
     *
     * @mbg.generated
     */
    public void setMattero(String mattero) {
        this.mattero = mattero == null ? null : mattero.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterOStr
     *
     * @return the value of check_matter.matterOStr
     *
     * @mbg.generated
     */
    public String getMatterostr() {
        return matterostr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterOStr
     *
     * @param matterostr the value for check_matter.matterOStr
     *
     * @mbg.generated
     */
    public void setMatterostr(String matterostr) {
        this.matterostr = matterostr == null ? null : matterostr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterP
     *
     * @return the value of check_matter.matterP
     *
     * @mbg.generated
     */
    public String getMatterp() {
        return matterp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterP
     *
     * @param matterp the value for check_matter.matterP
     *
     * @mbg.generated
     */
    public void setMatterp(String matterp) {
        this.matterp = matterp == null ? null : matterp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterPStr
     *
     * @return the value of check_matter.matterPStr
     *
     * @mbg.generated
     */
    public String getMatterpstr() {
        return matterpstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterPStr
     *
     * @param matterpstr the value for check_matter.matterPStr
     *
     * @mbg.generated
     */
    public void setMatterpstr(String matterpstr) {
        this.matterpstr = matterpstr == null ? null : matterpstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterQ
     *
     * @return the value of check_matter.matterQ
     *
     * @mbg.generated
     */
    public String getMatterq() {
        return matterq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterQ
     *
     * @param matterq the value for check_matter.matterQ
     *
     * @mbg.generated
     */
    public void setMatterq(String matterq) {
        this.matterq = matterq == null ? null : matterq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterQStr
     *
     * @return the value of check_matter.matterQStr
     *
     * @mbg.generated
     */
    public String getMatterqstr() {
        return matterqstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterQStr
     *
     * @param matterqstr the value for check_matter.matterQStr
     *
     * @mbg.generated
     */
    public void setMatterqstr(String matterqstr) {
        this.matterqstr = matterqstr == null ? null : matterqstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterR
     *
     * @return the value of check_matter.matterR
     *
     * @mbg.generated
     */
    public String getMatterr() {
        return matterr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterR
     *
     * @param matterr the value for check_matter.matterR
     *
     * @mbg.generated
     */
    public void setMatterr(String matterr) {
        this.matterr = matterr == null ? null : matterr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterRStr
     *
     * @return the value of check_matter.matterRStr
     *
     * @mbg.generated
     */
    public String getMatterrstr() {
        return matterrstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterRStr
     *
     * @param matterrstr the value for check_matter.matterRStr
     *
     * @mbg.generated
     */
    public void setMatterrstr(String matterrstr) {
        this.matterrstr = matterrstr == null ? null : matterrstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterS
     *
     * @return the value of check_matter.matterS
     *
     * @mbg.generated
     */
    public String getMatters() {
        return matters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterS
     *
     * @param matters the value for check_matter.matterS
     *
     * @mbg.generated
     */
    public void setMatters(String matters) {
        this.matters = matters == null ? null : matters.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.matterSStr
     *
     * @return the value of check_matter.matterSStr
     *
     * @mbg.generated
     */
    public String getMattersstr() {
        return mattersstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.matterSStr
     *
     * @param mattersstr the value for check_matter.matterSStr
     *
     * @mbg.generated
     */
    public void setMattersstr(String mattersstr) {
        this.mattersstr = mattersstr == null ? null : mattersstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.autographURL
     *
     * @return the value of check_matter.autographURL
     *
     * @mbg.generated
     */
    public String getAutographurl() {
        return autographurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.autographURL
     *
     * @param autographurl the value for check_matter.autographURL
     *
     * @mbg.generated
     */
    public void setAutographurl(String autographurl) {
        this.autographurl = autographurl == null ? null : autographurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_matter.allocationID
     *
     * @return the value of check_matter.allocationID
     *
     * @mbg.generated
     */
    public Long getAllocationid() {
        return allocationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_matter.allocationID
     *
     * @param allocationid the value for check_matter.allocationID
     *
     * @mbg.generated
     */
    public void setAllocationid(Long allocationid) {
        this.allocationid = allocationid;
    }
}