package com.sz.water.entity;

public class CheckAllocation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_allocation.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_allocation.userID
     *
     * @mbg.generated
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_allocation.communityID
     *
     * @mbg.generated
     */
    private Long communityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_allocation.taskID
     *
     * @mbg.generated
     */
    private Long taskid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_allocation.id
     *
     * @return the value of check_allocation.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_allocation.id
     *
     * @param id the value for check_allocation.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_allocation.userID
     *
     * @return the value of check_allocation.userID
     *
     * @mbg.generated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_allocation.userID
     *
     * @param userid the value for check_allocation.userID
     *
     * @mbg.generated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_allocation.communityID
     *
     * @return the value of check_allocation.communityID
     *
     * @mbg.generated
     */
    public Long getCommunityid() {
        return communityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_allocation.communityID
     *
     * @param communityid the value for check_allocation.communityID
     *
     * @mbg.generated
     */
    public void setCommunityid(Long communityid) {
        this.communityid = communityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_allocation.taskID
     *
     * @return the value of check_allocation.taskID
     *
     * @mbg.generated
     */
    public Long getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_allocation.taskID
     *
     * @param taskid the value for check_allocation.taskID
     *
     * @mbg.generated
     */
    public void setTaskid(Long taskid) {
        this.taskid = taskid;
    }
}