package com.sz.water.entity;

import java.util.Date;

public class CheckTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_task.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_task.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_task.projectNo
     *
     * @mbg.generated
     */
    private String projectno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_task.reportNo
     *
     * @mbg.generated
     */
    private String reportno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_task.writer
     *
     * @mbg.generated
     */
    private String writer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_task.inspector
     *
     * @mbg.generated
     */
    private String inspector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_task.auditor
     *
     * @mbg.generated
     */
    private String auditor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_task.version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_task.startDate
     *
     * @mbg.generated
     */
    private Date startdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_task.endDate
     *
     * @mbg.generated
     */
    private Date enddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_task.id
     *
     * @return the value of check_task.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_task.id
     *
     * @param id the value for check_task.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_task.name
     *
     * @return the value of check_task.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_task.name
     *
     * @param name the value for check_task.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_task.projectNo
     *
     * @return the value of check_task.projectNo
     *
     * @mbg.generated
     */
    public String getProjectno() {
        return projectno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_task.projectNo
     *
     * @param projectno the value for check_task.projectNo
     *
     * @mbg.generated
     */
    public void setProjectno(String projectno) {
        this.projectno = projectno == null ? null : projectno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_task.reportNo
     *
     * @return the value of check_task.reportNo
     *
     * @mbg.generated
     */
    public String getReportno() {
        return reportno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_task.reportNo
     *
     * @param reportno the value for check_task.reportNo
     *
     * @mbg.generated
     */
    public void setReportno(String reportno) {
        this.reportno = reportno == null ? null : reportno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_task.writer
     *
     * @return the value of check_task.writer
     *
     * @mbg.generated
     */
    public String getWriter() {
        return writer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_task.writer
     *
     * @param writer the value for check_task.writer
     *
     * @mbg.generated
     */
    public void setWriter(String writer) {
        this.writer = writer == null ? null : writer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_task.inspector
     *
     * @return the value of check_task.inspector
     *
     * @mbg.generated
     */
    public String getInspector() {
        return inspector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_task.inspector
     *
     * @param inspector the value for check_task.inspector
     *
     * @mbg.generated
     */
    public void setInspector(String inspector) {
        this.inspector = inspector == null ? null : inspector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_task.auditor
     *
     * @return the value of check_task.auditor
     *
     * @mbg.generated
     */
    public String getAuditor() {
        return auditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_task.auditor
     *
     * @param auditor the value for check_task.auditor
     *
     * @mbg.generated
     */
    public void setAuditor(String auditor) {
        this.auditor = auditor == null ? null : auditor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_task.version
     *
     * @return the value of check_task.version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_task.version
     *
     * @param version the value for check_task.version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_task.startDate
     *
     * @return the value of check_task.startDate
     *
     * @mbg.generated
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_task.startDate
     *
     * @param startdate the value for check_task.startDate
     *
     * @mbg.generated
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_task.endDate
     *
     * @return the value of check_task.endDate
     *
     * @mbg.generated
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_task.endDate
     *
     * @param enddate the value for check_task.endDate
     *
     * @mbg.generated
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
}