package com.sz.water.entity;

import java.util.Date;

public class Community {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.communityName
     *
     * @mbg.generated
     */
    private String communityname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.areaID
     *
     * @mbg.generated
     */
    private Integer areaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.street
     *
     * @mbg.generated
     */
    private String street;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.typeID
     *
     * @mbg.generated
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.maintenance
     *
     * @mbg.generated
     */
    private String maintenance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.contacts
     *
     * @mbg.generated
     */
    private String contacts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.telephone
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.rainNumber
     *
     * @mbg.generated
     */
    private Integer rainnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.sewageNumber
     *
     * @mbg.generated
     */
    private Integer sewagenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.basinID
     *
     * @mbg.generated
     */
    private Integer basinid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.sewageTreatmentID
     *
     * @mbg.generated
     */
    private Integer sewagetreatmentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.renovationTime
     *
     * @mbg.generated
     */
    private Date renovationtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.zbClass
     *
     * @mbg.generated
     */
    private String zbclass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.buildUnit
     *
     * @mbg.generated
     */
    private String buildunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.constructionUnit
     *
     * @mbg.generated
     */
    private String constructionunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.designUnit
     *
     * @mbg.generated
     */
    private String designunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.isShow
     *
     * @mbg.generated
     */
    private Boolean isshow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.isDele
     *
     * @mbg.generated
     */
    private Boolean isdele;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.creatTime
     *
     * @mbg.generated
     */
    private Date creattime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.areaScope
     *
     * @mbg.generated
     */
    private Object areascope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.txLng
     *
     * @mbg.generated
     */
    private Double txlng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.txLat
     *
     * @mbg.generated
     */
    private Double txlat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.Remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.id
     *
     * @return the value of community.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.id
     *
     * @param id the value for community.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.communityName
     *
     * @return the value of community.communityName
     *
     * @mbg.generated
     */
    public String getCommunityname() {
        return communityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.communityName
     *
     * @param communityname the value for community.communityName
     *
     * @mbg.generated
     */
    public void setCommunityname(String communityname) {
        this.communityname = communityname == null ? null : communityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.areaID
     *
     * @return the value of community.areaID
     *
     * @mbg.generated
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.areaID
     *
     * @param areaid the value for community.areaID
     *
     * @mbg.generated
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.street
     *
     * @return the value of community.street
     *
     * @mbg.generated
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.street
     *
     * @param street the value for community.street
     *
     * @mbg.generated
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.typeID
     *
     * @return the value of community.typeID
     *
     * @mbg.generated
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.typeID
     *
     * @param typeid the value for community.typeID
     *
     * @mbg.generated
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.maintenance
     *
     * @return the value of community.maintenance
     *
     * @mbg.generated
     */
    public String getMaintenance() {
        return maintenance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.maintenance
     *
     * @param maintenance the value for community.maintenance
     *
     * @mbg.generated
     */
    public void setMaintenance(String maintenance) {
        this.maintenance = maintenance == null ? null : maintenance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.contacts
     *
     * @return the value of community.contacts
     *
     * @mbg.generated
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.contacts
     *
     * @param contacts the value for community.contacts
     *
     * @mbg.generated
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.telephone
     *
     * @return the value of community.telephone
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.telephone
     *
     * @param telephone the value for community.telephone
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.rainNumber
     *
     * @return the value of community.rainNumber
     *
     * @mbg.generated
     */
    public Integer getRainnumber() {
        return rainnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.rainNumber
     *
     * @param rainnumber the value for community.rainNumber
     *
     * @mbg.generated
     */
    public void setRainnumber(Integer rainnumber) {
        this.rainnumber = rainnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.sewageNumber
     *
     * @return the value of community.sewageNumber
     *
     * @mbg.generated
     */
    public Integer getSewagenumber() {
        return sewagenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.sewageNumber
     *
     * @param sewagenumber the value for community.sewageNumber
     *
     * @mbg.generated
     */
    public void setSewagenumber(Integer sewagenumber) {
        this.sewagenumber = sewagenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.state
     *
     * @return the value of community.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.state
     *
     * @param state the value for community.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.basinID
     *
     * @return the value of community.basinID
     *
     * @mbg.generated
     */
    public Integer getBasinid() {
        return basinid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.basinID
     *
     * @param basinid the value for community.basinID
     *
     * @mbg.generated
     */
    public void setBasinid(Integer basinid) {
        this.basinid = basinid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.sewageTreatmentID
     *
     * @return the value of community.sewageTreatmentID
     *
     * @mbg.generated
     */
    public Integer getSewagetreatmentid() {
        return sewagetreatmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.sewageTreatmentID
     *
     * @param sewagetreatmentid the value for community.sewageTreatmentID
     *
     * @mbg.generated
     */
    public void setSewagetreatmentid(Integer sewagetreatmentid) {
        this.sewagetreatmentid = sewagetreatmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.renovationTime
     *
     * @return the value of community.renovationTime
     *
     * @mbg.generated
     */
    public Date getRenovationtime() {
        return renovationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.renovationTime
     *
     * @param renovationtime the value for community.renovationTime
     *
     * @mbg.generated
     */
    public void setRenovationtime(Date renovationtime) {
        this.renovationtime = renovationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.zbClass
     *
     * @return the value of community.zbClass
     *
     * @mbg.generated
     */
    public String getZbclass() {
        return zbclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.zbClass
     *
     * @param zbclass the value for community.zbClass
     *
     * @mbg.generated
     */
    public void setZbclass(String zbclass) {
        this.zbclass = zbclass == null ? null : zbclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.buildUnit
     *
     * @return the value of community.buildUnit
     *
     * @mbg.generated
     */
    public String getBuildunit() {
        return buildunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.buildUnit
     *
     * @param buildunit the value for community.buildUnit
     *
     * @mbg.generated
     */
    public void setBuildunit(String buildunit) {
        this.buildunit = buildunit == null ? null : buildunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.constructionUnit
     *
     * @return the value of community.constructionUnit
     *
     * @mbg.generated
     */
    public String getConstructionunit() {
        return constructionunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.constructionUnit
     *
     * @param constructionunit the value for community.constructionUnit
     *
     * @mbg.generated
     */
    public void setConstructionunit(String constructionunit) {
        this.constructionunit = constructionunit == null ? null : constructionunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.designUnit
     *
     * @return the value of community.designUnit
     *
     * @mbg.generated
     */
    public String getDesignunit() {
        return designunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.designUnit
     *
     * @param designunit the value for community.designUnit
     *
     * @mbg.generated
     */
    public void setDesignunit(String designunit) {
        this.designunit = designunit == null ? null : designunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.isShow
     *
     * @return the value of community.isShow
     *
     * @mbg.generated
     */
    public Boolean getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.isShow
     *
     * @param isshow the value for community.isShow
     *
     * @mbg.generated
     */
    public void setIsshow(Boolean isshow) {
        this.isshow = isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.sort
     *
     * @return the value of community.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.sort
     *
     * @param sort the value for community.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.isDele
     *
     * @return the value of community.isDele
     *
     * @mbg.generated
     */
    public Boolean getIsdele() {
        return isdele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.isDele
     *
     * @param isdele the value for community.isDele
     *
     * @mbg.generated
     */
    public void setIsdele(Boolean isdele) {
        this.isdele = isdele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.creatTime
     *
     * @return the value of community.creatTime
     *
     * @mbg.generated
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.creatTime
     *
     * @param creattime the value for community.creatTime
     *
     * @mbg.generated
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.areaScope
     *
     * @return the value of community.areaScope
     *
     * @mbg.generated
     */
    public Object getAreascope() {
        return areascope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.areaScope
     *
     * @param areascope the value for community.areaScope
     *
     * @mbg.generated
     */
    public void setAreascope(Object areascope) {
        this.areascope = areascope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.txLng
     *
     * @return the value of community.txLng
     *
     * @mbg.generated
     */
    public Double getTxlng() {
        return txlng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.txLng
     *
     * @param txlng the value for community.txLng
     *
     * @mbg.generated
     */
    public void setTxlng(Double txlng) {
        this.txlng = txlng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.txLat
     *
     * @return the value of community.txLat
     *
     * @mbg.generated
     */
    public Double getTxlat() {
        return txlat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.txLat
     *
     * @param txlat the value for community.txLat
     *
     * @mbg.generated
     */
    public void setTxlat(Double txlat) {
        this.txlat = txlat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.Remarks
     *
     * @return the value of community.Remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.Remarks
     *
     * @param remarks the value for community.Remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}