package com.sz.water.entity;

import java.util.Date;

public class Sewagetreatment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sewagetreatment.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sewagetreatment.range
     *
     * @mbg.generated
     */
    private Object range;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sewagetreatment.sewageTreatmentName
     *
     * @mbg.generated
     */
    private String sewagetreatmentname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sewagetreatment.creatTime
     *
     * @mbg.generated
     */
    private Date creattime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sewagetreatment.id
     *
     * @return the value of sewagetreatment.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sewagetreatment.id
     *
     * @param id the value for sewagetreatment.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sewagetreatment.range
     *
     * @return the value of sewagetreatment.range
     *
     * @mbg.generated
     */
    public Object getRange() {
        return range;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sewagetreatment.range
     *
     * @param range the value for sewagetreatment.range
     *
     * @mbg.generated
     */
    public void setRange(Object range) {
        this.range = range;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sewagetreatment.sewageTreatmentName
     *
     * @return the value of sewagetreatment.sewageTreatmentName
     *
     * @mbg.generated
     */
    public String getSewagetreatmentname() {
        return sewagetreatmentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sewagetreatment.sewageTreatmentName
     *
     * @param sewagetreatmentname the value for sewagetreatment.sewageTreatmentName
     *
     * @mbg.generated
     */
    public void setSewagetreatmentname(String sewagetreatmentname) {
        this.sewagetreatmentname = sewagetreatmentname == null ? null : sewagetreatmentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sewagetreatment.creatTime
     *
     * @return the value of sewagetreatment.creatTime
     *
     * @mbg.generated
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sewagetreatment.creatTime
     *
     * @param creattime the value for sewagetreatment.creatTime
     *
     * @mbg.generated
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }
}