package com.sz.water.dao;

import org.apache.ibatis.annotations.Mapper;

import com.sz.water.entity.Basin;

@Mapper
public interface BasinMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table basin
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table basin
	 *
	 * @mbg.generated
	 */
	int insert(Basin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table basin
	 *
	 * @mbg.generated
	 */
	int insertSelective(Basin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table basin
	 *
	 * @mbg.generated
	 */
	Basin selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table basin
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Basin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table basin
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Basin record);
}