package com.sz.water.dao;

import com.sz.water.entity.CheckMatterItem;

public interface CheckMatterItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_matter_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_matter_item
     *
     * @mbg.generated
     */
    int insert(CheckMatterItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_matter_item
     *
     * @mbg.generated
     */
    int insertSelective(CheckMatterItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_matter_item
     *
     * @mbg.generated
     */
    CheckMatterItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_matter_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CheckMatterItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_matter_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CheckMatterItem record);
}