package com.sz.water.dao;

import org.apache.ibatis.annotations.Mapper;

import com.sz.water.entity.CheckAllocation;

@Mapper
public interface CheckAllocationMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table check_allocation
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table check_allocation
	 *
	 * @mbg.generated
	 */
	int insert(CheckAllocation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table check_allocation
	 *
	 * @mbg.generated
	 */
	int insertSelective(CheckAllocation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table check_allocation
	 *
	 * @mbg.generated
	 */
	CheckAllocation selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table check_allocation
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(CheckAllocation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table check_allocation
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(CheckAllocation record);
}