package com.sz.water.dao;

import org.apache.ibatis.annotations.Mapper;

import com.sz.water.entity.Community;

@Mapper
public interface CommunityMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table community
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table community
	 *
	 * @mbg.generated
	 */
	int insert(Community record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table community
	 *
	 * @mbg.generated
	 */
	int insertSelective(Community record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table community
	 *
	 * @mbg.generated
	 */
	Community selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table community
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Community record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table community
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Community record);
}