package com.sz.water.dao;

import org.apache.ibatis.annotations.Mapper;

import com.sz.water.entity.Organization;

@Mapper
public interface OrganizationMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table organization
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table organization
	 *
	 * @mbg.generated
	 */
	int insert(Organization record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table organization
	 *
	 * @mbg.generated
	 */
	int insertSelective(Organization record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table organization
	 *
	 * @mbg.generated
	 */
	Organization selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table organization
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Organization record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table organization
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Organization record);
}