package com.sz.water.dao;

import org.apache.ibatis.annotations.Mapper;

import com.sz.water.entity.Role;

@Mapper
public interface RoleMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table role
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table role
	 *
	 * @mbg.generated
	 */
	int insert(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table role
	 *
	 * @mbg.generated
	 */
	int insertSelective(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table role
	 *
	 * @mbg.generated
	 */
	Role selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table role
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table role
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Role record);
}